models/user.py
import hashlib

from sqlalchemy import Column, String, Text

import config
import secret
from models.base_model import SQLMixin, db


class User(SQLMixin, db.Model):
    __tablename__ = 'User'
    """
    User 是一个保存用户数据的 model
    现在只有两个属性 username 和 password
    """
    username = Column(String(50), nullable=False)
    password = Column(String(100), nullable=False)
    image = Column(String(100), nullable=False, default='/images/3.jpg')
    email = Column(String(50), nullable=False, default=config.test_mail)
    signature = Column(String(50), nullable=False, default='这家伙很懒，什么个性签名都没有留下。')

    @staticmethod
    def salted_password(password, salt='$!@><?>HUI&DWQa`'):
        salted = hashlib.sha256((password + salt).encode('ascii')).hexdigest()
        return salted

    @classmethod
    def register(cls, form):
        name = form.get('username', '')
        print('register', form)
        if len(name) > 2 and User.one(username=name) is None:

            form['password'] = User.salted_password(form['password'])
            u = User.new(form)
            return u
        else:
            return None

    @classmethod
    def validate_login(cls, form):
        query = dict(
            username=form['username'],
            password=User.salted_password(form['password']),
        )
        print('validate_login', form, query)
        return User.one(**query)


routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory)
from flask.json import jsonify

from models.user import User

from utils import log

main = Blueprint('index', __name__)


def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.one(id=uid)
    return u


"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/")
def index():
    u = current_user()
    return render_template("index.html", user=u)


# @main.route("/register", methods=['POST'])
# def register():
#     # form = request.args
#     form = request.json
#     # 用类函数来判断
#     u = User.register(form)
#     if u is None:
#        response = jsonify({'register': False, 'error': '注册失败，用户名已存在'})
#        return response
#    else:
#        response = jsonify({'register': True, 'message': '注册成功，请点击登录'})
#        return response


@main.route("/login", methods=['POST'])
def login():
    print('request in login')
    form = request.json
    u = User.validate_login(form)
    if u is None:
        response = jsonify({'login': False, 'error': '登录失败，请检查账号和密码'})
        response.status_code = 401
        return response
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期
        session.permanent = True
        response = jsonify({'login': True, 'path': 'topic'})
        response.status_code = 200
        return response


@main.route("/logout")
def logout():
    session.pop('user_id')
    return redirect(url_for('bbs_topic.index'))


@main.route('/profile')
def profile():
    u = current_user()
    if u is None:
        return redirect(url_for('bbs_topic.index'))
    else:
        return render_template('profile.html', user=u)


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.find(id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', user=u)


def not_found(e):
    return render_template('404.html')


@main.route('/images/<filename>')
def image(filename):

    return send_from_directory('images', filename)



routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.board import Board
from routes import *

from models.topic import Topic


main = Blueprint('bbs_topic', __name__)


@main.route("/")
def index():
    u = current_user()
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    boards = Board.all()
    return render_template("topic/index.html", ms=ms, user=u, boards=boards, bid=board_id)


@main.route('/<int:id>')
# /topic/1
# @main.route('/')
# /topic?id=1
# zhihu.com/question/1/answer/2/comment/3/xxx/y
def detail(id):
    # id = int(request.args['id'])
    # http://localhost:3000/topic/1
    # m = Topic.one(id=id)
    m = Topic.get(id)
    u = current_user()
    # 不应该放在路由里面
    # m.views += 1
    # m.save()

    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, user=u)


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    u = current_user()
    m = Topic.add(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    boards = Board.all()
    u = current_user()
    token = new_csrf_token()
    return render_template("topic/new.html", user=u, boards=boards, token=token, bid=board_id)


routes/user.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort)
from werkzeug.datastructures import FileStorage

from routes import current_user, csrf_required, new_csrf_token
from models.topic import Topic
from models.reply import Reply
from models.user import User


main = Blueprint('bbs_user', __name__)

@main.route('/<string:username>')
def user(username):
    '''
    :param c_u 当前主页查询用户
    :param u 登录主页用户
    :param username:
    :return:
    '''
    c_u = User.one(username = username)
    u = current_user()
    t = Topic.all(user_id = c_u.id)
    r = Reply.all(user_id = c_u.id)
    rt = []
    for v in r:
        reply_topic = Topic.one(id = v.topic_id)
        if reply_topic not in rt:
            rt.append(reply_topic)
    t.reverse()
    rt.reverse()
    return render_template('user.html', user = u, c_user = c_u, topics = t, reply_topics = rt)


@main.route('/setting')
def setting():
    u = current_user()
    token = new_csrf_token()
    return render_template('settings.html', user = u, token = token)


@main.route('/profile', methods=['POST'])
@csrf_required
def profile():
    form = request.form
    u = current_user()
    User.update(u.id, username = form['username'], signature = form['signature'])
    return redirect(url_for('.setting'))


@main.route('/change_password', methods=['POST'])
@csrf_required
def change_password():
    form = request.form
    u = current_user()
    if u.password == User.salted_password(form['old_pass']):
        new_pass = User.salted_password(form['new_pass'])
        User.update(u.id, password = new_pass)
        return redirect(url_for('.setting'))
    else:
        abort(401)


@main.route('/change_avatar', methods=['POST'])
@csrf_required
def change_avatar():
    file: FileStorage = request.files['avatar']

    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.setting'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    {% block style %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/index.css">
    {% endblock %}
    <head>
<body>

<!-- navbar -->
{% block navbar %}
    <div class="navbar navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/topic">SPACEBY BBS</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>

                <ul class="nav navbar-nav pull-right">
                    {% if user %}
                        <li><a href="{{ url_for('bbs_user.setting') }}">设置</a></li>
                        <li><a href="{{ url_for('index.logout') }}">退出</a></li>
                    {% else %}
                        <li><a href='/'>登录</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block main %}
    <div id="main" class="row">
        <div id="sidebar" class="col-md-4 col-md-push-8">
            {% block sidebar %}
                <div class="box">
                    <div class="header inner">
                        <span class="box_title">个人信息</span>
                    </div>
                    {% if user %}
                        <div class='inner'>
                            <div class='user_card'>
                                <a href="{{ url_for('bbs_user.user', username=user.username) }}">
                                    <img class='user_avatar' src="{{ user.image }}"
                                         title="{{ user.username }}"/>
                                </a>
                                <span class='user_name'>
                            <a href="{{ url_for('bbs_user.user', username=user.username) }}">{{ user.username }}</a>
                        </span>

                                <div class='board clearfix'>
                                    <div class='floor'>
                                        <span class='big'>积分: 0 </span>
                                    </div>
                                </div>
                                <div class="space clearfix"></div>
                                <span class="signature">"{{ user.signature }}"</span>
                            </div>
                        </div>
                    {% else %}
                        <div class='inner'>
                            <span>Spaceby bbs</span>
                            <div>
                                您可以
                                <a href='{{ url_for('index.index') }}'>登录</a>
                            </div>
                        </div>
                    {% endif %}
                </div>
            {% endblock sidebar %}
        </div>

        <div id="content" class="col-md-8 col-md-pull-4">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
{% endblock main %}


{% block script %}
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
    <script src="/static/js/ajax.js"></script>
{% endblock script %}


</body>

templates/bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css">
    <style>
        body {
            background-color: #c6c9d2;
        }

        .navbar {
            background-color: #ffffff;
            box-shadow: 0 1px 5px #6f6f6f;
        }

        .pull-right {
            float: right;
        }

        #main {
            width: 90%;
            margin: 15px auto;
            min-height: 600px;
        }

        #footer {
            background-color: #ffffff;
            float: bottom;
        }

        .container {
            width: 90%;
        }

        #content {
        }

        #sidebar {
            float: right;
        }

        .header {
            height: 40px;

            border-bottom: 1px solid #e2e2e2;
            background-color: #f6f6f6;
            border-top-left-radius: 3px;
            border-top-right-radius: 3px;
        }

        .inner {
            padding: 10px;
            font-size: 14px;
            line-height: 150%;
            text-align: left;
        }

        .box {
            background-color: #ffffff;
            box-shadow: 0 1px 5px #6f6f6f;
            margin-bottom: 20px;
            border-radius: 3px;
        }

        .box_title {
            color: #23527c;
        }

        .topic_tab {
            margin-right: 10px;
        }

        .topic_tab.current_tab {
            background-color: #377db8;
            color: white;
            padding: 3px 4px;
            border-radius: 3px;
        }

        .cell {
            padding: 10px;
            line-height: 120%;
            text-align: left;
            border-bottom: 1px solid #e2e2e2;
        }

        img.user_avatar {
            border-radius: 3px;
        }
    </style>
</head>
<body>
<div class="navbar navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">SPACEBY BBS</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>

            <ul class="nav navbar-nav pull-right">
                <li><a href="#">login</a></li>
                <li><a href="#">register</a></li>
            </ul>
        </div>
    </div>
</div>

<div id="main" class="row">
    <div id="sidebar" class="col-md-4">
        <div class="box">
            <div class="header inner">
                <span class="box_title">个人信息</span>
            </div>
            <div class='inner'>
                <div class='user_card'>
                    <a href="">
                        <img class='user_avatar' src="https://cdn.v2ex.com/gravatar/ba2efe2183cac7bbadc29a079565716f?s=48&d=retro"
                             title="username"/>
                    </a>
                    <span class='user_name'>
                        <a href="username">username</a>
                    </span>

                    <div class='board clearfix'>
                        <div class='floor'>
                            <span class='big'>积分: 0 </span>
                        </div>
                    </div>
                    <div class="space clearfix"></div>
                    <span class="signature">"这个逼很懒，没有签名"</span>
                </div>
            </div>
        </div>
    </div>

    <div id="content" class="col-md-8">
        <div class="box">
            <div class="header inner">
                <a href="" class="topic_tab current_tab">全部</a>
                <a href="" class="topic_tab">python</a>
                <a href="" class="topic_tab">linux</a>
                <a href="" class="topic_tab">flask</a>
                <a href="" class="topic_tab">django</a>
            </div>
            <div id="topiclist" class="">
                <div class="cell">
                    <div class="topic_title_wrapper">
                        <a class="topic_title" href="">
                            React Suite 做了一个有意思的决定
                        </a>
                        <span>1 / 6</span>
                    </div>
                </div>
                <div class="cell">
                    <div class="topic_title_wrapper">
                        <a class="topic_title" href="">
                            React Suite 做了一个有意思的决定
                        </a>
                        <span>1 / 6</span>
                    </div>
                </div>
                <div class="cell">
                    <div class="topic_title_wrapper">
                        <a class="topic_title" href="">
                            React Suite 做了一个有意思的决定
                        </a>
                        <span>1 / 6</span>
                    </div>
                </div>
                <div class="cell">
                    <div class="topic_title_wrapper">
                        <a class="topic_title" href="">
                            React Suite 做了一个有意思的决定
                        </a>
                        <span>1 / 6</span>
                    </div>
                </div>
                <div class="cell">
                    <div class="topic_title_wrapper">
                        <a class="topic_title" href="">
                            React Suite 做了一个有意思的决定
                        </a>
                        <span>1 / 6</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="box"></div>
    </div>
</div>

<div id="footer">
    <div class="container">
        <div class="links">
            <a class="dark" href="">@spaceby</a>
            |
            <a class="dark" href="https://github.com/spacexzm/BBS">源码地址</a>
        </div>
    </div>
</div>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}
    SPACEBY BBS
{% endblock %}

{% block style %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/login.css">
{% endblock %}


{% block main %}
    <div id="id-user-form" class="container">
        <form class="form-login">
            <h2 class="form-login-heading">Please login in</h2>
            <div class="username-form">
                <label for="inputUsername" class="sr-only">Username</label>
                <input type="text" id="id-input-username"
                       class="form-control" placeholder="Username"
                       pattern="[A-z0-9]{3,}" required autofocus>
            </div>

            <div class="password-form">
                <label for="inputPassword" class="sr-only">Password</label>
                <input type="password" id="id-input-password"
                       class="form-control" placeholder="Password"
                       pattern="[A-z0-9]{3,}" required>
            </div>

            <div class="mesage-show">
                <p id="id-error-message" class="alert-danger"></p>
            </div>
            <button id="id-button-login" class="btn btn-lg btn-primary btn-block btn-login">Login in</button>
        </form>
       <!-- <div class="toggle">
            <button id="id-button-toggle" class="btn btn-lg btn-primary btn-block to-register">切换注册</button>
        </div>
    </div> -->
{% endblock %}

{% block script %}
    {{ super() }}
    <script src="/static/js/login.js"></script>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form>
    <input type="text" name="user_name" placeholder="user_name" pattern="[A-z]{3}">
    <input type="text" name="user_name" placeholder="user_name" minlength="3">
    <button type="submit">提交</button>
</form>


<input type="text" name="user_name" placeholder="user_name" pattern="[0-9]{3}">
<input type="text" name="user_name" placeholder="user_name" minlength="3">
</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
</head>
<body>
    <h1>用户资料页面</h1>
    <div>
        {{ user.id }}
    </div>
    <div>
        {{ user.username }}
    </div>
    <div>
        {{ user.password }}
    </div>
</body>
</html>

templates/settings.html
{% extends "base.html" %}

{% block title %}
    设置
{% endblock %}

{% block sidebar %}
    {{ super() }}
    <div class="box">
        <div class="inner">
            <a href="/topic/new?board_id=-1" class="create_topic_btn">
                <span class="btn btn-primary">发布话题</span>
            </a>
        </div>
    </div>
{% endblock %}

{% block content %}

    <div class="box">
        <div class="header inner">
            <a href=""><span>主页</span></a>
            <span> / 设置</span>
        </div>
        <div class="inner">
            <form id="setting_form" class="form-horizontal"
                  action="{{ url_for('bbs_user.profile', token = token) }}" method="post">
                <div class="form-group">
                    <label id="id_username" for="id_input_username">用户名</label>
                    <input id="id_input_username" type="text" class="form-control" name="username"
                           placeholder="{{ user.username }}" value="{{ user.username }}">
                </div>
                <div class="form-group">
                    <label for="">个性签名</label>
                    <textarea id="id_textarea_signature" class="form-control" rows="3" name="signature"
                              style="width: 250px;">{{ user.signature }}</textarea>
                </div>

                <button type="submit" class="btn btn-primary">保存设置</button>
            </form>
        </div>
    </div>

    <div class="box">
        <div class="header inner">
            <span class="box_title">更改密码</span>
        </div>
        <div class="inner">
            <form id="change_pass_form" class="form-horizontal"
                  action="{{ url_for('bbs_user.change_password', token = token) }}" method="post">
                <div class="form-group">
                    <label for="id_input_oldpass">当前密码</label>
                    <input id="id_input_oldpass" type="password" class="form-control" name="old_pass">
                </div>
                <div class="form-group">
                    <label for="id_input_newpass">新密码</label>
                    <input id="id_input_newpass" type="password" class="form-control" name="new_pass">
                </div>

                <button type="submit" class="btn btn-primary">更改密码</button>
            </form>
        </div>
    </div>

    <div class="box">
        <div class="header inner">
            <span class="box_title">上传头像</span>
        </div>
        <div class="inner">
            <form id="change_avatar_form"
                  class="form-horizontal"
                  action="{{ url_for('bbs_user.change_avatar', token = token) }}"
                  enctype="multipart/form-data"
                  method="post"
            >
                <div class="form-group">
                    <input type="file" id="id_input_avatar" name="avatar">
                    <p class="help-block">选择本地头像上传。</p>
                </div>

                <button type="submit" class="btn btn-primary">上传头像</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/user.html
{% extends "base.html" %}

{% block title %}
    {{ c_user.username }} 的个人主页
{% endblock %}

{% block content %}
    <div class="box">
        <div class="header inner">
            <a href=""><span>主页</span></a>
            <span> / {{ c_user.username }}</span>
        </div>
        <div class='inner'>
            <div class='user_card'>
                <a href="{{ url_for('bbs_user.user', username=c_user.username) }}">
                    <img class='user_avatar' src="{{ c_user.image }}"
                         title="{{ c_user.username }}"/>
                </a>
                <span class='user_name'>
                            <a href="{{ url_for('bbs_user.user', username=c_user.username) }}">{{ c_user.username }}</a>
                        </span>

                <div class='board clearfix'>
                    <div class='floor'>
                        <span class='big'>积分: 0 </span>
                    </div>
                </div>
                <div class="space clearfix"></div>
                <span class="signature">"{{ c_user.signature }}"</span>
            </div>
        </div>
    </div>

    <div class="box">
        <div class="header inner">
            <span class="box_title">最近创建的话题</span>
        </div>
        <div class="inner">
            {% for topic in topics %}
                <div class="cell">
                    <div class="topic_title_wrapper">
                        <a class="topic_title" href="{{ url_for('bbs_topic.detail', id=topic.id) }}">
                            {{ topic.title }}
                        </a>
                        <span>{{ topic.replies() | count }} / {{ topic.views }}</span>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="box">
        <div class="header inner">
            <span class="box_title">最近参与的话题</span>
        </div>
        <div class="inner">
            {% for reply_topic in reply_topics %}
                <div class="cell">
                    <div class="topic_title_wrapper">
                        <a class="topic_title" href="{{ url_for('bbs_topic.detail', id=reply_topic.id) }}">
                            {{ reply_topic.title }}
                        </a>
                        <span>{{ reply_topic.replies() | count }} / {{ reply_topic.views }}</span>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}