models/topic.py
import time

from sqlalchemy import String, Integer, Column, Text, UnicodeText, Unicode

from models import Model
from models.base_model import SQLMixin, db
from models.user import User
from models.reply import Reply


class Topic(SQLMixin, db.Model):
    views = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)
    board_id = Column(Integer, nullable=False, default=0)

    @classmethod
    def add(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(form)
        return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

    def replies(self):
        ms = Reply.all(topic_id=self.id)
        return ms

    def reply_count(self):
        count = len(self.replies())
        return count

routes/reply.py
from flask import (
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user

from models.reply import Reply


main = Blueprint('bbs_reply', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    u = current_user()
    print('DEBUG', form)
    m = Reply.add(form, user_id=u.id)
    return redirect(url_for('bbs_topic.detail', id=m.topic_id))


routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.board import Board
from routes import *

from models.topic import Topic


main = Blueprint('bbs_topic', __name__)


@main.route("/")
def index():
    u = current_user()
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    boards = Board.all()
    return render_template("topic/index.html", ms=ms, user=u, boards=boards, bid=board_id)


@main.route('/<int:id>')
# /topic/1
# @main.route('/')
# /topic?id=1
# zhihu.com/question/1/answer/2/comment/3/xxx/y
def detail(id):
    # id = int(request.args['id'])
    # http://localhost:3000/topic/1
    # m = Topic.one(id=id)
    m = Topic.get(id)
    u = current_user()
    # 不应该放在路由里面
    # m.views += 1
    # m.save()

    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, user=u)


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    u = current_user()
    m = Topic.add(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    boards = Board.all()
    u = current_user()
    token = new_csrf_token()
    return render_template("topic/new.html", user=u, boards=boards, token=token, bid=board_id)


routes/user.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort)
from werkzeug.datastructures import FileStorage

from routes import current_user, csrf_required, new_csrf_token
from models.topic import Topic
from models.reply import Reply
from models.user import User


main = Blueprint('bbs_user', __name__)

@main.route('/<string:username>')
def user(username):
    '''
    :param c_u 当前主页查询用户
    :param u 登录主页用户
    :param username:
    :return:
    '''
    c_u = User.one(username = username)
    u = current_user()
    t = Topic.all(user_id = c_u.id)
    r = Reply.all(user_id = c_u.id)
    rt = []
    for v in r:
        reply_topic = Topic.one(id = v.topic_id)
        if reply_topic not in rt:
            rt.append(reply_topic)
    t.reverse()
    rt.reverse()
    return render_template('user.html', user = u, c_user = c_u, topics = t, reply_topics = rt)


@main.route('/setting')
def setting():
    u = current_user()
    token = new_csrf_token()
    return render_template('settings.html', user = u, token = token)


@main.route('/profile', methods=['POST'])
@csrf_required
def profile():
    form = request.form
    u = current_user()
    User.update(u.id, username = form['username'], signature = form['signature'])
    return redirect(url_for('.setting'))


@main.route('/change_password', methods=['POST'])
@csrf_required
def change_password():
    form = request.form
    u = current_user()
    if u.password == User.salted_password(form['old_pass']):
        new_pass = User.salted_password(form['new_pass'])
        User.update(u.id, password = new_pass)
        return redirect(url_for('.setting'))
    else:
        abort(401)


@main.route('/change_avatar', methods=['POST'])
@csrf_required
def change_avatar():
    file: FileStorage = request.files['avatar']

    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.setting'))

templates/topic/detail.html
{% extends "base.html" %}

{% block title %}
    {{ topic.title }}
{% endblock %}

{% block style %}
    {{ super() }}
    <link rel="stylesheet" href="https://unpkg.com/mditor@1.0.5/dist/css/mditor.min.css"/>
{% endblock %}

{% block sidebar %}
    <div class="box">
        <div class="header inner">
            <span class="box_title">作者信息</span>
        </div>
        <div class='inner'>
            <div class='user_card'>
                <a href="{{ url_for('bbs_user.user', username=topic.user().username) }}">
                    <img class='user_avatar' src="{{ topic.user().image }}"
                         title="{{ topic.user().username }}"/>
                </a>
                <span class='user_name'>
                            <a href="{{ url_for('bbs_user.user', username=topic.user().username) }}">{{ topic.user().username }}</a>
                        </span>

                <div class='board clearfix'>
                    <div class='floor'>
                        <span class='big'>积分: 0 </span>
                    </div>
                </div>
                <div class="space clearfix"></div>
                <span class="signature">"{{ topic.user().signature }}"</span>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="box">
        <div class='header inner'>
            <h3>{{ topic.title }}</h3>
            <div class="changes">
                    <span>
                        发布于 {{ topic.created_time | format_time }}
                    </span>
                <span>
                        作者 <a
                        href="{{ url_for('bbs_user.user', username=topic.user().username ) }}">{{ topic.user().username }}</a>
                    </span>
                <span>
                        {{ topic.views }} 次浏览
                    </span>
                <span>
                        来自 问答
                    </span>
            </div>
        </div>

        <div class='inner topic'>
            <div class='topic_content'>
                <div class="markdown-text">{{ topic.content }}</div>
            </div>
        </div>
    </div>

    <div class="box">
        <div class='header inner'>
            <span class="box_title">
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        <div class="reply_list">
            {% for r in topic.replies() %}
                {% set u = r.user() %}
                <div class='cell'>
                    <div class='user_info'>
                        <a class='reply_author'>
                            {{ u.username }}
                        </a>
                        <a class="reply_info">
                            {{ loop.index }}楼 / {{ loop.length }}楼 •
                            <span class="reply_time" data-created_time="{{ r.created_time }}"></span>
                        </a>
                    </div>
                    <div class='reply_content from--{{ r.user().username }}'>
                        <div class="markdown-text">{{ r.content }}</div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>

    <div class="box">
        <div class="header inner">
            <span class="col_fade">添加回复</span>
        </div>
        <div id="comment_form">
            <form action="{{ url_for('bbs_reply.add') }}" method="post">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <textarea id="editor" name="content"></textarea>
                <button type="submit" class="btn btn-primary">添加回复</button>
            </form>
        </div>
    </div>

{% endblock %}

{% block script %}
    {{ super() }}
    <script src="https://unpkg.com/mditor@1.0.5/dist/js/mditor.min.js"></script>
    <script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
    <script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
    <script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
    <script>
        const markContents = function () {
            // markdown -> html 的处理放在高亮前面
            // 因为高亮是针对 html 格式的
            // lang -> language 不需要转 prism 自动转了
            let contentDivs = es('.markdown-text')
            for (let i = 0; i < contentDivs.length; i++) {
                let contentDiv = contentDivs[i]
                let content = marked(contentDiv.textContent)
                contentDiv.innerHTML = content
            }
        }

        const highlight = function () {
            // 自动加载对应的语言 不然要手动加入各个语言的 js
            Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
        }

        const registerTimer = function () {
            setInterval(function () {
                let times = es('.reply_time')
                for (let i = 0; i < times.length; i++) {
                    let t = times[i]
                    let time = Number(t.dataset.created_time)
                    let now = Math.floor(new Date() / 1000)
                    let delta = now - time
                    let s = `${delta} 秒前`
                    t.innerText = s
                }
            }, 1000)
        }

        const mditor = Mditor.fromTextarea(document.getElementById('editor'));

        //获取或设置编辑器的值
        mditor.on('ready', function () {
            console.log(mditor.value);
            mditor.value = '** hello **';
        });

        const __main = function () {
            markContents()
            highlight()
            registerTimer()
        }

        __main()

    </script>

{% endblock %}


templates/topic/index.html
{% extends "base.html" %}

{% block title %}
    论坛主页
{% endblock %}

{% block sidebar %}
    {{ super() }}
    {% if user %}
        <div class="box">
            <div class="inner">
                <a href="/topic/new?board_id={{ bid }}" class="create_topic_btn">
                    <span class="btn btn-primary">发布话题</span>
                </a>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="box">
        <div class="header inner">
            <a href="/topic?board_id=-1" class="topic_tab current_tab">全部</a>
            {% for board in boards %}
                <a href="/topic?board_id={{ board.id }}" class="topic_tab">{{ board.title }}</a>
            {% endfor %}
        </div>
        <div id="topiclist" class="">
            {% for t in ms %}
                <div class="cell">
                    <div class="topic_title_wrapper">
                        <a class="topic_title" href="{{ url_for('bbs_topic.detail', id=t.id) }}">
                            {{ t.title }}
                        </a>
                        <span>{{ t.replies() | count }} / {{ t.views }}</span>
                        {# count(t.replies()) #}
                        {# <span>{{ t.reply_count() }} / {{ t.views }}</span> #}
                        {#len(Reply.all(topic_id=t.id))#}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}






templates/topic/new.html
{% extends "base.html" %}

{% block title %}
    发布话题
{% endblock %}

{% block style %}
    {{ super() }}
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
{% endblock %}

{% block sidebar %}
    {{ super() }}
    <div class="box">
        <div class="header inner">
            <span class="box_title">
                markdown示例
            </span>
        </div>
        <div class="inner">
            <ol>
                <li>### 单行的标题</li>
                <li>**粗体**</li>
                <li>`console.log('行内代码')`</li>
                <li>```js\n code \n``` 标记代码块</li>
                <li>[内容](链接)</li>
                <li>![文字说明](图片链接)</li>
            </ol>
            <span class="inner"><a href="https://segmentfault.com/markdown" target="_blank">Markdown 文档</a></span>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="box">
        <div class="header inner">
            <span class="box_title">发布话题</span>
        </div>
        <div class="inner">
            <form id="id_form_createtopic" method="post" action="{{ url_for('.add', token=token) }}">
                <fieldset>
                    <textarea autofocus class='form-control' id='title' name='title' rows='1'
                              placeholder="标题字数 10 字以上"></textarea>
                    <span class="tab-selector">选择版块：</span>
                    <div class="form-group">
                        <select name="board_id" id="id_board" class="form-control">
                            {% for b in boards %}
                                {% if bid == b.id %}
                                    <option value="{{ b.id }}" selected>{{ b.title }}</option>
                                {% else %}
                                    <option value="{{ b.id }}">{{ b.title }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <div class='markdown_editor in_editor'>
                        <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20'
                                          placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                            <button class="btn btn-primary" type="submit">提交</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock content %}

{% block script %}
    {{ super() }}
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
    <script>
        (function () {
            var editor = new Editor();
            editor.render($('.editor')[0]);
        })();
    </script>
{% endblock %}